# Generated by Django 5.1.2 on 2024-11-30 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookborrowmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowmodel',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookborrowmodel',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.bookmodel'),
        ),
    ]
