# Generated by Django 5.1.2 on 2024-12-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_commented_on_commentmodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_img',
            field=models.ImageField(upload_to='book/media/uploads/'),
        ),
    ]
