# Generated by Django 5.1.2 on 2024-11-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='loan_approve',
        ),
    ]
